### PR TITLE
Create a victor control package

### PR DESCRIPTION
**Pull request by PeterMitrano**
This will be used for gazebo_ros_control. The empty launch file is a placeholder. semantically, it is where the launch for real victor goes, which for now is empty

### CODE REVIEW

**Comment by bsaund** [comment]
I'm confused - I thought `arm_robots` had been used to control real victor, but empty launch files seems to disagree

**Comment by PeterMitrano** [comment]
that launch file is not used when controlling real victor, there's a launch file in arm_robots that does that

**Review by bsaund — APPROVED** [review]
The gazebo controllers worked for me when I tested a few weeks ago

**Comment by PeterMitrano** [comment]
see https://github.com/UM-ARM-Lab/arm_robots/blob/master/arm_robots/launch/victor.launch
it calls the two launch files here depending on gazebo or not, and so we need this empty one to exist for simplicity

**Pull request merged**
